schema_version: 1

context:
  name: livelike
  version: "1.5.3"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 417c530becf177d5304dcfd573f700d0fe4570b8a6c08a9d6f8976da55639ede

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - awkward >=2.6
    - certifi >=2025.10.5
    - deprecation
    - dill
    - geopandas >=1.1
    - libpysal >=4.12
    - likeness_vitals
    - multiprocess >=0.70.15
    - networkx >=3.2
    - numpy >=1.26
    - packaging
    - pandas >=2.2
    - pyarrow
    - pygris >=0.1.6
    - scipy >=1.12
    - shapely >=2.0

tests:
  - python:
      imports:
        - livelike
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A Population Synthesizer for High Demographic Resolution Analysis.
  license: LicenseRef-UT-BATTELLE
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/likeness-pop/
  documentation: https://github.com/likeness-pop/livelike/

extra:
  recipe-maintainers:
    - jvtcl
    - jGaboardi
